name: Deploy Vite React App

on:
  push:
    branches:
      - main  # or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20  # or your preferred version

    - name: Install Dependencies
      run: |
        cd frontend  # change if your Vite project is in a different folder
        npm install

    - name: Build Vite App
      run: |
        cd frontend
        npm run build

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22  # change if your SSH runs on another port
        script: |
          cd ./OdysseyAnalytic
          dos2unix backendDeploy.sh
          ./frontendDeploy.sh
